export const clienti_mock = [
  {
    nome: "Marco",
    cognome: "Rossi",
    strada: "Viale vialoso",
    numero_civico: "8",
    provincia: "Caserta (CE)",
    comune: "Caserta",
    codicefiscale: "MRCRSS90A26B963F",
    telefono: "111",
    interventi: [
      {
        id: 1,
        data_chiamata: new Date("2024-01-25"),
        data_completamento: false,
        data_assegnamento: false,
        motivazione: "Caldaia rotta",
        note_per_tecnico: "Chiamare al telefono",
        note_del_tecnico: "",
        stato: "nuovo",
        tecnico: "",
      },
      {
        id: 2,
        data_chiamata: new Date("2024-01-25"),
        data_completamento: false,
        data_assegnamento: new Date("2024-01-26"),
        motivazione: "Caldaia rotta",
        note_per_tecnico: "Chiamare al telefono",
        note_del_tecnico: "buon cliente",
        stato: "assegnato",
        tecnico: "Danilo",
      },
      {
        id: 3,
        data_chiamata: new Date("2024-01-25"),
        data_completamento: new Date("2024-01-26"),
        data_assegnamento: new Date("2024-01-26"),
        motivazione: "Riscaldamento rotta",
        note_per_tecnico: "",
        note_del_tecnico: "Cambiato pezzo",
        stato: "completo",
        tecnico: "Mimmo",
      },
    ],
    garanzia: {},
    manutenzione: {},
  },

  {
    nome: "Vincenzo",
    cognome: "Rossi",
    strada: "Viale vialoso",
    numero_civico: "6",
    provincia: "Caserta (CE)",
    comune: "Casal di Principe",
    codicefiscale: "VNCRSS73A26B872P",
    telefono: "222",
    interventi: [],
    garanzia: {},
    manutenzione: {},
  },

  {
    nome: "Francesco",
    cognome: "Esposito",
    strada: "Viale lenin",
    numero_civico: "3",
    provincia: "Caserta (CE)",
    comune: "Villa Literno",
    codicefiscale: "FRNDNN83A26L844N",
    telefono: "333",
    interventi: [
      {
        id: 4,
        data_chiamata: "2024-01-10",
        tecnico: "Danilo",
        motivazione: "Si vede un rumore",
        note_per_tecnico: "",
        note_del_tecnico: "",
        stato: "completo",
      },
    ],
    garanzia: {},
    manutenzione: {},
  },
];
