export const giornate_mock = [
  {
    id: 1,
    giorno: new Date(),
    tecnico: "Danilo",
    ore_impegnate: 6,
    modificabile: true,
    interventi: [],
  },
  {
    id: 2,
    giorno: new Date(),
    tecnico: "Mimmo",
    ore_impegnate: 6.5,
    modificabile: true,
  },
  {
    id: 3,
    giorno: new Date("2024-01-01"),
    tecnico: "Danilo",
    ore_impegnate: 6,
    modificabile: false,
    interventi: [
      {
        id: 1,
        data_chiamata: new Date("2024-01-25"),
        data_completamento: false,
        data_assegnamento: false,
        motivazione: "Caldaia rotta",
        note_per_tecnico: "Chiamare al telefono",
        note_del_tecnico: "",
        stato: "nuovo",
        tecnico: "",
        cliente: {
          nome: "Marco",
          cognome: "Rossi",
          numero: "111",
        },
      },
      {
        id: 2,
        data_chiamata: new Date("2024-01-25"),
        data_completamento: false,
        data_assegnamento: new Date("2024-01-26"),
        motivazione: "Caldaia rotta",
        note_per_tecnico: "Chiamare al telefono",
        note_del_tecnico: "buon cliente",
        stato: "assegnato",
        tecnico: "Danilo",
        cliente: {
          nome: "Marco",
          cognome: "Rossi",
          numero: "111",
        },
      },
    ],
  },
  {
    id: 4,
    giorno: new Date("2026-01-01"),
    tecnico: "Danilo",
    ore_impegnate: 6,
    modificabile: false,
  },
];
