export const interventi_mock = [
  {
    id: 1,
    data_chiamata: new Date("2024-01-25").getDate(),
    data_completamento: false,
    data_assegnamento: false,
    motivazione: "Caldaia rotta",
    note_per_tecnico: "Chiamare al telefono",
    note_del_tecnico: "",
    stato: "nuovo",
    tecnico: "",
    cliente: {
      nome: "Marco",
      cognome: "Rossi",
      numero: "111",
    },
  },
  {
    id: 2,
    data_chiamata: new Date("2024-01-25"),
    data_completamento: false,
    data_assegnamento: new Date("2024-01-26"),
    motivazione: "Caldaia rotta",
    note_per_tecnico: "Chiamare al telefono",
    note_del_tecnico: "buon cliente",
    stato: "assegnato",
    tecnico: "Danilo",
    cliente: {
      nome: "Marco",
      cognome: "Rossi",
      numero: "111",
    },
  },
  {
    id: 3,
    data_chiamata: new Date("2024-01-25"),
    data_completamento: new Date("2024-01-26"),
    data_assegnamento: new Date("2024-01-26"),
    motivazione: "Riscaldamento rotta",
    note_per_tecnico: "",
    note_del_tecnico: "Cambiato pezzo",
    stato: "completo",
    tecnico: "Mimmo",
    cliente: {
      nome: "Marco",
      cognome: "Rossi",
      numero: "111",
    },
  },
  {
    id: 4,
    data_chiamata: new Date("2024-01-10").toDateString(),
    data_chiamata: new Date("2024-01-12"),
    data_chiamata: new Date("2024-01-11"),
    tecnico: "Danilo",
    motivazione: "Si vede un rumore",
    note_per_tecnico: "",
    note_del_tecnico: "",
    stato: "assegnato",
    cliente: {
      nome: "Francesco",
      cognome: "Esposito",
      numero: "333",
    },
  },
];
